[theme]
# The preset Streamlit theme that your custom theme inherits from.
base="dark"

# Primary accent color for interactive elements.
primaryColor="#764ba2"

# Background color for the main content area.
backgroundColor="#090c11"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#1c2029"

# Color used for almost all text.
textColor="#ffffff"

# Font family for all text in the app.
# "sans serif", "serif", or "monospace" are the supported options.
font="sans serif"
